services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./logging:/app/logging
      - ./datasets:/app/datasets
      - ./observability:/app/observability
      - ./data:/app/data
    working_dir: /app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - api
